openapi: 3.0.0
info:
  title: API UP ACECA
  description: '-----'
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/DanieleCerioni/UPACEA/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: ODM
  description: Tutte le informazioni riguardanti gli organi di manovra
- name: RGDM
  description: Tutte le informazioni riguardanti il rilevatore di guasti multidirezionale
- name: UP
  description: Tutte le informazioni riguradanti l'unità periferica
paths:
  /odms:
    get:
      tags:
      - odm
      operationId: getAllOdm
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OdmListResponse'
    post:
      tags:
      - odm
      operationId: addOdm
      requestBody:
        description: add an odm to the platform
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Odm'
      responses:
        "405":
          description: Invalid input
          content: {}
  /odm/{idOdm}:
    get:
      tags:
      - odm
      operationId: getOdm
      parameters:
      - name: idOdm
        in: path
        description: ID of odm to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OdmResponse'
        "400":
          description: Invalid ID supplied
          content: {}
        "404":
          description: Odm not found
          content: {}
components:
  schemas:
    Phase:
      type: object
      properties:
        name:
          type: string
          enum:
          - P1
          - P2
          - P3
        current:
          type: integer
          format: int32
          default: 0
        voltage:
          type: integer
          format: int32
          default: 0
    Odm:
      type: object
      properties:
        id:
          type: integer
          format: int64
        identifier:
          type: string
        tipology:
          type: string
        vendor:
          type: string
        model:
          type: string
        actualStatus:
          type: string
          description: status odm
          enum:
          - "true"
          - "false"
          - DISCONNECTED
        phases:
          type: array
          items:
            $ref: '#/components/schemas/Phase'
    Rgdm:
      type: object
      properties:
        id:
          type: integer
          format: int64
        identifier:
          type: string
        tipology:
          type: string
        vendor:
          type: string
        model:
          type: string
        actualStatus:
          type: string
          description: stato odm
          enum:
          - "true"
          - "false"
          - DISCONNECTED
        statusAlarms:
          type: string
        statusProtection:
          type: string
        phases:
          type: array
          items:
            $ref: '#/components/schemas/Phase'
    UP:
      type: object
      properties:
        id:
          type: integer
          format: int64
        info:
          type: string
        alarm:
          type: string
        configuration:
          $ref: '#/components/schemas/Setup'
    Setup:
      type: object
      properties:
        STM:
          $ref: '#/components/schemas/STM'
        GOOSE:
          $ref: '#/components/schemas/GOOSE'
        Network:
          $ref: '#/components/schemas/Network'
    STM:
      type: object
      properties:
        firstIp:
          type: string
        secondIp:
          type: string
        netInteface:
          type: string
    GOOSE:
      type: object
      properties:
        routing:
          type: string
        macAddress:
          type: string
        repetitionInterval:
          type: string
        netInterface:
          type: string
        bpfFilter:
          type: string
    Network:
      type: object
      properties:
        networkInterfaces:
          type: array
          items:
            $ref: '#/components/schemas/NetworkInterface'
    NetworkInterface:
      type: object
      properties:
        name:
          type: string
          description: ETH0, ETH1, WLAN0
        status:
          type: string
        configure:
          type: string
        ipAddress:
          type: string
        subnetMask:
          type: string
        gateway:
          type: string
        dnsServers:
          type: string
    ErrorMessage:
      type: object
      properties:
        errorCode:
          type: string
        errorMessage:
          type: string
    ErrorResponse:
      properties:
        payload:
          $ref: '#/components/schemas/ErrorMessage'
      allOf:
      - $ref: '#/components/schemas/ApiResponse'
      - type: object
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        payload:
          type: object
          properties: {}
    OdmResponse:
      properties:
        payload:
          $ref: '#/components/schemas/Odm'
      allOf:
      - $ref: '#/components/schemas/ApiResponse'
      - type: object
    OdmListResponse:
      properties:
        payload:
          type: array
          items:
            $ref: '#/components/schemas/Odm'
      allOf:
      - $ref: '#/components/schemas/ApiResponse'
      - type: object
